// Polly 工作台：班級週期／本期設定 v2
(function(){
 const KEY='polly_class_cycles_v1';
 let cycles={}; try{cycles=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch(e){}
 const save=()=>localStorage.setItem(KEY,JSON.stringify(cycles));
 const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
 function allClasses(){try{if(typeof state!=='undefined'&&state&&Array.isArray(state.classes))return state.classes;}catch(e){} try{if(typeof POLLY_CLASS_DATA!=='undefined')return POLLY_CLASS_DATA;}catch(e){} return [];}
 function key(c){return String(c.code||c.id||c.name||'');}
 function isoFromROC(s){const m=String(s||'').match(/^(\d{3})\/(\d{1,2})\/(\d{1,2})$/);if(!m)return /^\d{4}-\d{2}-\d{2}$/.test(String(s||''))?s:'';return `${Number(m[1])+1911}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;}
 function rec(c){const k=key(c);if(!cycles[k])cycles[k]={start:isoFromROC(c.start),end:isoFromROC(c.end),prepDeadline:'',history:[]};return cycles[k];}
 function dayBefore(s){if(!s)return '';const d=new Date(s+'T12:00:00');d.setDate(d.getDate()-1);return d.toISOString().slice(0,10);}
 function addButtons(){document.querySelectorAll('#classList .class-card, #classList .card').forEach(card=>{if(card.querySelector('.cycleBtn'))return;const txt=card.innerText||'';const c=allClasses().find(x=>txt.includes(x.code||'___')||txt.includes(x.name||'___'));if(!c)return;const b=document.createElement('button');b.className='btn cycleBtn';b.textContent='📅 本期設定';b.style.marginTop='8px';b.onclick=e=>{e.stopPropagation();open(c);};card.appendChild(b);});}
 function ensureModal(){let m=document.getElementById('cycleModal');if(m)return m;m=document.createElement('div');m.id='cycleModal';m.style.cssText='display:none;position:fixed;inset:0;z-index:10000;background:#0005;align-items:center;justify-content:center;padding:16px';m.innerHTML=`<div id="cycleSheet" style="width:min(92vw,480px);max-height:88vh;overflow:auto;background:var(--yellow,#FFF2CC);border:1px solid #eadcae;border-radius:24px;padding:18px;box-shadow:0 18px 50px #0003"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px"><h2 style="margin:0;font-size:21px">📅 班級本期設定</h2><button class="btn" id="cycleClose" aria-label="關閉" style="width:42px;height:42px;padding:0;border-radius:14px;font-size:22px;background:#fffdf8">×</button></div><div id="cycleBody"></div></div>`;document.body.appendChild(m);m.querySelector('#cycleClose').onclick=()=>m.style.display='none';m.onclick=e=>{if(e.target===m)m.style.display='none'};return m;}
 function field(label,id,value){return `<label style="display:block;margin:12px 0 0;font-weight:800">${label}<input id="${id}" type="date" value="${esc(value)}" style="display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:12px 14px;border:1px solid var(--line);border-radius:13px;background:#fffdf8;color:var(--ink);font-size:16px;min-height:48px"></label>`}
 function open(c){const r=rec(c);if(!r.prepDeadline)r.prepDeadline=dayBefore(r.start);const m=ensureModal();m.querySelector('#cycleBody').innerHTML=`<div style="background:#fff9e7;border:1px solid #eadfb8;border-radius:15px;padding:12px 14px;margin-bottom:8px"><b style="font-size:18px">${esc(c.name||c.code)}</b><div style="font-size:12px;color:var(--muted);margin-top:3px">${esc(c.code||'')}</div></div>${field('開課日期','cyStart',r.start)}${field('結束日期','cyEnd',r.end)}${field('開學準備截止日','cyPrep',r.prepDeadline)}<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px"><button class="btn primary" id="cySave" style="min-height:46px">儲存本期</button><button class="btn" id="cyNew" style="min-height:46px;background:#fffdf8">🔄 建立新一期</button></div>${r.history.length?`<div style="margin-top:16px;padding-top:14px;border-top:1px solid #eadcae"><b>歷史期別</b>${r.history.map(h=>`<div style="font-size:13px;color:var(--muted);padding:6px 0">${esc(h.start)} ～ ${esc(h.end)}</div>`).join('')}</div>`:''}`;m.style.display='flex';m.querySelector('#cySave').onclick=()=>{r.start=m.querySelector('#cyStart').value;r.end=m.querySelector('#cyEnd').value;r.prepDeadline=m.querySelector('#cyPrep').value;save();m.style.display='none';};m.querySelector('#cyNew').onclick=()=>{if(!confirm('建立新一期後，會保留本期日期到歷史紀錄，並將新一期的準備確認重新開始。確定嗎？'))return;if(r.start||r.end)r.history.unshift({start:r.start,end:r.end,prepDeadline:r.prepDeadline,closedAt:new Date().toISOString()});r.start='';r.end='';r.prepDeadline='';save();try{const wp=JSON.parse(localStorage.getItem('polly_work_prep_v2')||'{}');['school','camp'].forEach(sec=>{if(wp.prep&&wp.prep[sec]&&wp.prep[sec][key(c)]&&Array.isArray(wp.prep[sec][key(c)].items))wp.prep[sec][key(c)].items.forEach(i=>i.done=false);});localStorage.setItem('polly_work_prep_v2',JSON.stringify(wp));}catch(e){} open(c);};}
 function init(){addButtons();setTimeout(addButtons,800);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,700);
 document.addEventListener('click',()=>setTimeout(addButtons,100));
})();