(() => {
'use strict';
const URL='https://ttfamytleguygqbwqmat.supabase.co';
const KEY='sb_publishable_xxFZSy912kCrw1lAlmY16g_wV8Zb9KS';
const WORK='polly-workspace-v1', PREP='polly_work_prep_v2', FLOW='polly_class_workflow_v1';
const ADMIT_KEYS=['polly-admissions-v1','polly-admissions'];
let client=null,user=null,timer=null,applying=false,lastSaved='';
const el=id=>document.getElementById(id);
function parse(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
function admissions(){for(const k of ADMIT_KEYS){const v=localStorage.getItem(k);if(v){try{return {key:k,data:JSON.parse(v)}}catch(e){}}}return {key:ADMIT_KEYS[0],data:[]}}
function snapshot(){const a=admissions();return {workspace:parse(WORK,{}),admissions:a.data,workPrep:parse(PREP,{prep:{school:{},camp:{}},admin:[]}),classWorkflow:parse(FLOW,{extraClasses:[],events:[],reviews:[]})}}
function hasUseful(s){return (s?.workspace?.records?.length||0)+(s?.workspace?.classes?.length||0)+(Array.isArray(s?.admissions)?s.admissions.length:0)+Object.keys(s?.workPrep?.prep?.school||{}).length+(s?.classWorkflow?.events?.length||0)+(s?.classWorkflow?.reviews?.length||0)>0}
function inject(){if(el('pollyCloudBar'))return;const d=document.createElement('div');d.id='pollyCloudBar';d.style.cssText='position:fixed;right:12px;bottom:78px;z-index:90;background:#fff;border:1px solid #ece6d7;border-radius:14px;padding:9px 11px;box-shadow:0 6px 24px #0002;font:12px system-ui;max-width:280px';d.innerHTML='<div style="font-weight:800">☁️ 雲端同步</div><div id="pollyCloudStatus" style="margin-top:3px;color:#817b6e">準備中…</div><div id="pollyCloudActions" style="margin-top:7px"></div>';document.body.appendChild(d)}
function status(t){if(el('pollyCloudStatus'))el('pollyCloudStatus').textContent=t}function actions(h){if(el('pollyCloudActions'))el('pollyCloudActions').innerHTML=h}
function authForm(){actions('<div style="display:grid;gap:6px"><input id="pollyCloudEmail" type="email" placeholder="Email" style="padding:8px"><input id="pollyCloudPassword" type="password" placeholder="密碼（至少 6 碼）" style="padding:8px"><div><button class="btn primary" id="pollyCloudLogin">登入</button> <button class="btn" id="pollyCloudSignup">第一次使用／註冊</button></div></div>');el('pollyCloudLogin').onclick=login;el('pollyCloudSignup').onclick=signup}
function creds(){const email=(el('pollyCloudEmail')?.value||'').trim(),password=el('pollyCloudPassword')?.value||'';if(!email||password.length<6){status('請輸入 Email 與至少 6 碼密碼');return null}return {email,password}}
async function login(){const c=creds();if(!c)return;const {error}=await client.auth.signInWithPassword(c);status(error?'登入失敗：'+error.message:'✓ 登入成功')}
async function signup(){const c=creds();if(!c||!confirm('建立 Polly 工作台同步帳號嗎？'))return;const {error}=await client.auth.signUp({email:c.email,password:c.password,options:{emailRedirectTo:'https://zhihan840531.github.io/polly-schedule/'}});status(error?'註冊失敗：'+error.message:'帳號已建立')}
async function logout(){await client.auth.signOut();location.reload()}
async function pullOrSeed(){if(!user)return;status('正在比對雲端資料…');const {data,error}=await client.from('polly_cloud_state').select('workspace,admissions,work_prep,class_workflow,updated_at').eq('user_id',user.id).maybeSingle();if(error){status('讀取失敗：'+error.message);return}const local=snapshot();if(!data){if(hasUseful(local))await push(true);return}const cloud={workspace:data.workspace||{},admissions:data.admissions||[],workPrep:data.work_prep||local.workPrep,classWorkflow:data.class_workflow||local.classWorkflow};if(!hasUseful(cloud)&&hasUseful(local)){await push(true);return}applying=true;localStorage.setItem(WORK,JSON.stringify(cloud.workspace));const a=admissions();localStorage.setItem(a.key,JSON.stringify(cloud.admissions));localStorage.setItem(PREP,JSON.stringify(cloud.workPrep));localStorage.setItem(FLOW,JSON.stringify(cloud.classWorkflow));applying=false;lastSaved=JSON.stringify(snapshot());status('✓ 已從雲端同步');setTimeout(()=>location.reload(),350)}
async function push(force=false){if(!user||applying)return;const s=snapshot(),str=JSON.stringify(s);if(!force&&str===lastSaved)return;status('同步中…');const {error}=await client.from('polly_cloud_state').upsert({user_id:user.id,workspace:s.workspace,admissions:s.admissions,work_prep:s.workPrep,class_workflow:s.classWorkflow},{onConflict:'user_id'});if(error){status('同步失敗：'+error.message);return}lastSaved=str;status('✓ 已同步 '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))}
function watch(){lastSaved=JSON.stringify(snapshot());clearInterval(timer);timer=setInterval(()=>push(false),2500);window.addEventListener('polly-data-changed',()=>push(false));window.addEventListener('pagehide',()=>push(false))}
function logged(){status('已登入 '+(user?.email||''));actions('<button class="btn" id="pollyCloudNow">立即同步</button> <button class="btn" id="pollyCloudLogout">登出</button>');el('pollyCloudNow').onclick=()=>push(true);el('pollyCloudLogout').onclick=logout}
async function initClient(){inject();if(!window.supabase){status('雲端元件載入失敗');return}client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getSession();user=data.session?.user||null;client.auth.onAuthStateChange((e,s)=>{user=s?.user||null;if(user){logged();setTimeout(async()=>{await pullOrSeed();watch()},0)}else{authForm();status('尚未登入')}});if(!user){authForm();status('請登入');return}logged();await pullOrSeed();watch()}
function boot(){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=initClient;document.head.appendChild(s)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();